[theme]
primaryColor="#050114"
backgroundColor="#f2f4f5"
secondaryBackgroundColor="#c5e1f0"
textColor="#050114"
font="sans serif"




[theme_Dark]
primaryColor="#FF7903"
backgroundColor="#0E1117"
secondaryBackgroundColor="#31333F"
textColor="#FAFAFA"
font="sans serif"
