[theme]
primaryColor="#F63366"
backgroundColor="#97d2e8"
secondaryBackgroundColor="#433db3"
textColor="#050114"
font="sans serif"




[theme_Dark]
primaryColor="#FF7903"
backgroundColor="#0E1117"
secondaryBackgroundColor="#31333F"
textColor="#FAFAFA"
font="sans serif"
